export const FUTSAL_LEXICON = [
 {term:'Diagonal',cat:'Movimento ofensivo',aliases:['diagonal','corte diagonal','agredir diagonal'],meaning:'Movimento sem bola em trajetória diagonal para criar linha de passe, atacar espaço ou romper uma linha defensiva.',intent:'move_diagonal'},
 {term:'Paralela',cat:'Movimento ofensivo',aliases:['paralela','pela paralela','agredir paralela'],meaning:'Movimento ou passe em profundidade junto ao corredor lateral, aproximadamente paralelo à linha lateral.',intent:'move_parallel'},
 {term:'Apoio',cat:'Movimento ofensivo',aliases:['apoio','aproximação','aproximar','dar apoio'],meaning:'Movimento para oferecer ao portador uma solução de passe curta, lateral ou atrás da bola.',intent:'support'},
 {term:'Desmarcação de apoio',cat:'Movimento ofensivo',aliases:['desmarcação de apoio','vem apoiar','baixa para apoiar'],meaning:'Movimento sem bola em direção ao portador para criar uma linha de passe segura.',intent:'support'},
 {term:'Desmarcação de ruptura',cat:'Movimento ofensivo',aliases:['ruptura','desmarcação de ruptura','rompe','ataca profundidade'],meaning:'Movimento sem bola para atacar o espaço atrás ou entre defensores.',intent:'breakaway'},
 {term:'Ganhar costas',cat:'Movimento ofensivo',aliases:['ganhar costas','ganha costas','nas costas','ataca costas'],meaning:'Projetar-se para o espaço atrás do defensor e retirar-lhe controlo visual simultâneo da bola e do atacante.',intent:'breakaway'},
 {term:'Afundar',cat:'Movimento ofensivo',aliases:['afundar','afunda','ganhar fundo','vai ao fundo','linha de fundo','fundo do campo'],meaning:'Atacar profundidade até à zona de fundo para criar passe atrasado, cruzamento ou desequilíbrio.',intent:'deep_run'},
 {term:'Sobreposição',cat:'Movimento ofensivo',aliases:['sobreposição','sobrepoe','overlap','cruzamento por trás'],meaning:'Movimento de um jogador por trás do portador para ocupar o corredor exterior ou libertado.',intent:'overlap'},
 {term:'Troca',cat:'Movimento coletivo',aliases:['troca','troca posição','permutação','permuta'],meaning:'Mudança coordenada de posição entre dois jogadores.',intent:'switch'},
 {term:'Rotação',cat:'Movimento coletivo',aliases:['rotação','roda','rodar posições','circulação posicional'],meaning:'Sequência coordenada de trocas de posição para manter ocupação racional dos espaços e criar desequilíbrios.',intent:'rotation'},
 {term:'Movimentos sincronizados',cat:'Movimento coletivo',aliases:['sincronizados','movimentos sincronizados','ao mesmo tempo'],meaning:'Dois ou mais movimentos simultâneos orientados para o mesmo objetivo tático.',intent:'synchronised'},
 {term:'Bloqueio',cat:'Movimento coletivo',aliases:['bloqueio','bloqueia','screen'],meaning:'Posicionamento/movimento para dificultar legalmente a ação do defensor e libertar um colega.',intent:'block'},
 {term:'Corta-luz',cat:'Movimento coletivo',aliases:['corta luz','deixa passar','dummy'],meaning:'Ação em que um jogador simula intervenção na bola e a deixa seguir para criar vantagem a outro.',intent:'dummy'},
 {term:'Entrelinhas',cat:'Espaço',aliases:['entrelinhas','entre linhas','espaço entre linhas'],meaning:'Espaço situado entre duas linhas defensivas adversárias.',intent:'between_lines'},
 {term:'Corredor lateral',cat:'Espaço',aliases:['corredor','corredor lateral','ala','faixa lateral'],meaning:'Zona vertical imaginária próxima da linha lateral.',intent:'wide_channel'},
 {term:'Corredor central',cat:'Espaço',aliases:['corredor central','meio','zona central','centro'],meaning:'Zona longitudinal central da quadra, relevante para progressão, cobertura e finalização.',intent:'central_channel'},
 {term:'Largura',cat:'Princípio ofensivo',aliases:['largura','abrir','abre campo','jogar largo'],meaning:'Ocupar espaços laterais para aumentar a distância entre defensores e criar corredores interiores.',intent:'width'},
 {term:'Profundidade',cat:'Princípio ofensivo',aliases:['profundidade','esticar','jogar profundo','ataca profundidade'],meaning:'Ocupar ou atacar espaços mais próximos da baliza adversária para alongar a defesa.',intent:'depth'},
 {term:'Linha de passe',cat:'Relação com bola',aliases:['linha de passe','linha passe','opção de passe'],meaning:'Possibilidade real de ligação por passe entre portador e companheiro num determinado instante.',intent:'passing_line'},
 {term:'Passe em progressão',cat:'Relação com bola',aliases:['passe em progressão','passe vertical','passe para frente'],meaning:'Passe que faz a equipa avançar territorialmente e supera espaço ou oposição.',intent:'progressive_pass'},
 {term:'Passe ao pivô',cat:'Relação com bola',aliases:['bola no pivô','passe no pivô','joga no pivô','pivo'],meaning:'Ligação com o jogador de referência mais avançado para fixar, apoiar, rodar ou finalizar.',intent:'pivot_pass'},
 {term:'Bola de tempo no pivô',cat:'Relação com bola',aliases:['bola de tempo','bola de tempo no pivô'],meaning:'Passe ao pivô coordenado com o movimento dos colegas para explorar o momento da receção.',intent:'pivot_timed_pass'},
 {term:'Tabela',cat:'Combinação ofensiva',aliases:['tabela','um dois','1-2','parede'],meaning:'Combinação rápida em que o portador passa, desmarca e recebe de volta.',intent:'one_two'},
 {term:'Terceiro homem',cat:'Combinação ofensiva',aliases:['terceiro homem','terceiro jogador'],meaning:'Combinação em que um terceiro jogador recebe após a interação de dois colegas, explorando a reação defensiva.',intent:'third_player'},
 {term:'Bola no meio',cat:'Finalização',aliases:['bola no meio','mete no meio','dá no meio','passe atrás','bola atrás','cutback'],meaning:'Passe da zona profunda/fundo para uma zona interior, normalmente para um jogador que entra de frente para finalizar.',intent:'cutback'},
 {term:'Bola aérea',cat:'Relação com bola',aliases:['bola aérea','passe aéreo','bola pelo ar','cruzamento aéreo'],meaning:'Passe ou cruzamento com trajetória aérea para ultrapassar oposição ou encontrar uma zona de finalização.',intent:'aerial_pass'},
 {term:'Primeiro poste',cat:'Finalização',aliases:['primeiro poste','1 poste','poste próximo'],meaning:'Poste mais próximo da posição da bola.',intent:'near_post'},
 {term:'Segundo poste',cat:'Finalização',aliases:['segundo poste','2 poste','poste contrário','segundo pau'],meaning:'Poste mais afastado da posição da bola; zona prioritária de ataque em muitas ações de finalização no futsal.',intent:'far_post'},
 {term:'Ataque ao segundo poste',cat:'Finalização',aliases:['ataca segundo poste','entra segundo poste','fecha segundo poste','aparece segundo poste'],meaning:'Movimento sem bola para ocupar o poste contrário e finalizar passe, remate cruzado ou bola aérea.',intent:'far_post_run'},
 {term:'Remate cruzado',cat:'Finalização',aliases:['remate cruzado','remata cruzado','chute cruzado'],meaning:'Remate dirigido transversalmente em relação à posição do executante, frequentemente explorando o poste contrário.',intent:'cross_shot'},
 {term:'Finalização',cat:'Finalização',aliases:['finaliza','finalização','remata','chuta','faz golo'],meaning:'Ação destinada a concluir a jogada com remate à baliza.',intent:'finish'},
 {term:'Fixo',cat:'Posição',aliases:['fixo','fecho'],meaning:'Jogador de campo habitualmente mais recuado, importante na organização defensiva e construção.',intent:'role_fixo'},
 {term:'Ala',cat:'Posição',aliases:['ala','ala direito','ala esquerdo'],meaning:'Jogador que atua sobretudo nos corredores laterais, ligando construção, criação e recomposição.',intent:'role_ala'},
 {term:'Pivô',cat:'Posição',aliases:['pivô','pivo','pivot'],meaning:'Referência ofensiva mais avançada, capaz de receber sob pressão, fixar, assistir, rodar e finalizar.',intent:'role_pivot'},
 {term:'Guarda-redes',cat:'Posição',aliases:['guarda redes','gr','goleiro','portero'],meaning:'Jogador que protege a baliza e participa ativamente na organização, cobertura e construção.',intent:'role_gk'},
 {term:'Guarda-redes avançado',cat:'Posição',aliases:['goleiro linha','guarda redes avançado','gr avançado','5x4','cinco para quatro'],meaning:'Utilização do guarda-redes ou de jogador com função equivalente como elemento adicional na posse ofensiva.',intent:'flying_gk'},
 {term:'3:1',cat:'Sistema',aliases:['3:1','3-1','tres um'],meaning:'Estrutura ofensiva com três jogadores em zonas de construção e um pivô mais avançado.',intent:'system_31'},
 {term:'4:0',cat:'Sistema',aliases:['4:0','4-0','quatro zero'],meaning:'Estrutura ofensiva sem pivô fixo, baseada em mobilidade, trocas e ocupação dinâmica de espaços.',intent:'system_40'},
 {term:'2:2',cat:'Sistema',aliases:['2:2','2-2','dois dois','quadrado'],meaning:'Estrutura com dois jogadores mais baixos e dois mais altos, podendo assumir diferentes relações ofensivas/defensivas.',intent:'system_22'},
 {term:'Linha defensiva',cat:'Organização defensiva',aliases:['linha defensiva','linha de defesa','primeira linha','segunda linha','terceira linha'],meaning:'Linha imaginária correspondente à altura dos defensores; a primeira é a mais avançada e as restantes sucedem-se até ao GR.',intent:'defensive_line'},
 {term:'Primeira linha defensiva',cat:'Organização defensiva',aliases:['primeira linha defensiva','1 linha defensiva','primeira linha'],meaning:'Linha defensiva representada pelo defensor ou defensores mais avançados.',intent:'first_def_line'},
 {term:'Linha ofensiva',cat:'Organização ofensiva',aliases:['linha ofensiva','linha de ataque','linha ofensiva alta'],meaning:'Referência de altura/ocupação dos jogadores em posse usada pelo motor para descrever a estrutura ofensiva; não é um termo padronizado no glossário FIFA.',intent:'offensive_line'},
 {term:'Defesa ativa',cat:'Organização defensiva',aliases:['defesa ativa','pressiona bola','pressão ativa'],meaning:'Defesa que pressiona a bola procurando provocar erro e recuperar a posse.',intent:'active_defence'},
 {term:'Defesa passiva',cat:'Organização defensiva',aliases:['defesa passiva','espera','sem pressão'],meaning:'Defesa que não pressiona imediatamente e espera o erro adversário.',intent:'passive_defence'},
 {term:'Defesa fechada',cat:'Organização defensiva',aliases:['defesa fechada','bloco fechado','fechar dentro'],meaning:'Defesa compacta e organizada no setor defensivo, reduzindo espaços úteis ao adversário.',intent:'closed_defence'},
 {term:'Bloco alto',cat:'Organização defensiva',aliases:['bloco alto','pressão alta','pressionar alto'],meaning:'Organização defensiva adiantada para condicionar a construção adversária perto da sua baliza.',intent:'high_block'},
 {term:'Bloco médio',cat:'Organização defensiva',aliases:['bloco médio','meio bloco'],meaning:'Organização defensiva em altura intermédia, equilibrando pressão, espaço e proteção da profundidade.',intent:'mid_block'},
 {term:'Bloco baixo',cat:'Organização defensiva',aliases:['bloco baixo','defender baixo','baixar bloco'],meaning:'Organização defensiva próxima da própria baliza, priorizando compactação e proteção de zonas interiores.',intent:'low_block'},
 {term:'Pressão',cat:'Organização defensiva',aliases:['pressão','pressiona','pressing','aperta'],meaning:'Ação de reduzir tempo e espaço do portador para condicionar decisão, passe ou condução.',intent:'press'},
 {term:'Pressão ao portador',cat:'Organização defensiva',aliases:['pressiona portador','pressão na bola','aperta bola'],meaning:'Pressão direta sobre o jogador com bola.',intent:'ball_press'},
 {term:'Cobertura',cat:'Organização defensiva',aliases:['cobertura','cobre','faz cobertura'],meaning:'Apoio defensivo escalonado a um colega, preparado para intervir se este for ultrapassado.',intent:'cover'},
 {term:'Dobra',cat:'Organização defensiva',aliases:['dobra','dobrar','dois na bola'],meaning:'Ação de um segundo defensor aproximar-se para aumentar pressão/controlo sobre o portador.',intent:'double_team'},
 {term:'Troca de marcação',cat:'Organização defensiva',aliases:['troca marcação','troca','switch defensivo'],meaning:'Transferência coordenada da responsabilidade de marcação entre defensores.',intent:'marking_switch'},
 {term:'Marcação individual',cat:'Organização defensiva',aliases:['individual','homem a homem','marcação individual'],meaning:'Organização em que cada defensor assume prioritariamente um adversário.',intent:'man_mark'},
 {term:'Marcação zonal',cat:'Organização defensiva',aliases:['zona','zonal','marcação por zona'],meaning:'Organização em que a prioridade é proteger espaços e ajustar referências conforme bola e adversários.',intent:'zone_mark'},
 {term:'Temporização',cat:'Transição defensiva',aliases:['temporiza','temporização','atrasa ataque'],meaning:'Ação de atrasar a progressão adversária para permitir reorganização defensiva.',intent:'delay'},
 {term:'Recuo',cat:'Transição defensiva',aliases:['recuo','recua','retorna','recomposição'],meaning:'Movimento de retorno da equipa sem bola para recuperar organização defensiva.',intent:'retreat'},
 {term:'Recomposição defensiva',cat:'Transição defensiva',aliases:['recomposição','recompor','retorno defensivo'],meaning:'Ação coletiva de recuperar rapidamente posições e relações defensivas após perda da bola.',intent:'defensive_recovery'},
 {term:'Transição ofensiva',cat:'Transição',aliases:['transição ofensiva','sair rápido','contra ataque','contra-ataque'],meaning:'Mudança da fase defensiva para ofensiva após recuperar a posse, explorando eventual desorganização adversária.',intent:'off_transition'},
 {term:'Transição defensiva',cat:'Transição',aliases:['transição defensiva','reagir à perda','após perda'],meaning:'Mudança imediata da fase ofensiva para defensiva após perder a posse.',intent:'def_transition'},
 {term:'Superioridade numérica',cat:'Princípio tático',aliases:['superioridade','vantagem numérica','2x1','3x2','4x3'],meaning:'Ter mais jogadores que o adversário numa determinada zona, ação ou momento.',intent:'numerical_advantage'},
 {term:'Superioridade posicional',cat:'Princípio tático',aliases:['vantagem posicional','superioridade posicional'],meaning:'Ocupar posições que proporcionam melhores linhas de passe, receção ou progressão que a organização adversária.',intent:'positional_advantage'},
 {term:'Fixar',cat:'Princípio tático',aliases:['fixa','fixar','prende defensor','atrai defensor'],meaning:'Condicionar um defensor pela posição ou condução para libertar espaço ou colega noutro local.',intent:'fix_defender'},
 {term:'Atrair',cat:'Princípio tático',aliases:['atrai','atrair','chama pressão'],meaning:'Provocar aproximação defensiva para libertar espaço noutra zona.',intent:'draw_pressure'},
 {term:'Fechar linha de passe',cat:'Princípio defensivo',aliases:['fecha linha de passe','corta linha de passe','nega passe'],meaning:'Posicionar-se para impedir ou tornar arriscada uma opção de passe adversária.',intent:'deny_pass'},
 {term:'Orientar pressão',cat:'Princípio defensivo',aliases:['orienta','induz','leva para fora','fecha dentro'],meaning:'Condicionar o portador para progredir na direção desejada pela organização defensiva.',intent:'show_direction'},
 {term:'Sombra',cat:'Princípio defensivo',aliases:['sombra','acompanha','shadow'],meaning:'Defender acompanhando o atacante sem o impedir diretamente, controlando espaço e progressão.',intent:'shadow'},
 {term:'Leitura de jogo',cat:'Decisão',aliases:['leitura','ler jogo','leitura de jogo'],meaning:'Interpretar posições, movimentos, espaços e relações para tomar a decisão tática adequada.',intent:'game_reading'},
 {term:'Velocidade de execução',cat:'Decisão',aliases:['velocidade execução','executa rápido','ritmo de execução'],meaning:'Tempo necessário para realizar uma ação técnica/tática.',intent:'execution_speed'},
 {term:'Controlo do jogo',cat:'Decisão',aliases:['controla jogo','controlo do jogo','controlar ritmo'],meaning:'Gerir ritmo, velocidade e cadência das ações que influenciam a partida.',intent:'game_control'},
 {term:'Bola parada',cat:'Situação especial',aliases:['bola parada','set piece','jogada ensaiada'],meaning:'Situação reiniciada por canto, lateral, livre, saída de centro ou outra reposição, frequentemente com combinação preparada.',intent:'set_piece'},
 {term:'Canto',cat:'Situação especial',aliases:['canto','corner','escanteio'],meaning:'Reposição a partir do canto ofensivo, com combinações para remate, segundo poste, bloqueio ou passe atrás.',intent:'corner'},
 {term:'Lateral',cat:'Situação especial',aliases:['lateral','fora','kick in','reposição lateral'],meaning:'Reposição da bola pela linha lateral, podendo iniciar combinação ensaiada.',intent:'kick_in'},
 {term:'Livre',cat:'Situação especial',aliases:['livre','falta','free kick'],meaning:'Reposição após infração, direta ou indireta conforme as leis do jogo.',intent:'free_kick'},
 {term:'Saída de pressão',cat:'Construção',aliases:['saída de pressão','sair da pressão','quebrar pressão'],meaning:'Organização para superar uma pressão adversária através de apoios, mobilidade, passe, condução ou jogo direto.',intent:'press_escape'},
 {term:'Construção',cat:'Construção',aliases:['construção','saída de bola','iniciar jogo'],meaning:'Fase de organização da posse desde zonas baixas para progredir de forma controlada.',intent:'build_up'},
 {term:'Jogo direto',cat:'Construção',aliases:['jogo direto','bola direta','direto no pivô'],meaning:'Progressão rápida para uma referência avançada ou espaço profundo, reduzindo passes de construção.',intent:'direct_play'},
 {term:'Ataque posicional',cat:'Ataque',aliases:['ataque posicional','ataque organizado','ataque estático'],meaning:'Ataque realizado contra uma defesa organizada, valorizando ocupação racional e circulação.',intent:'positional_attack'},
 {term:'Ataque rápido',cat:'Ataque',aliases:['ataque rápido','sair rápido'],meaning:'Ataque iniciado imediatamente após recuperação ou passe do GR, procurando defesa ainda desorganizada.',intent:'quick_attack'},
]

export function normaliseFutsalText(text=''){
 return text.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ').trim()
}
export function lexiconMatches(text=''){
 const n=normaliseFutsalText(text)
 return FUTSAL_LEXICON.filter(e=>e.aliases.some(a=>n.includes(normaliseFutsalText(a))))
}
export function lexiconEntry(term=''){
 const n=normaliseFutsalText(term)
 return FUTSAL_LEXICON.find(e=>normaliseFutsalText(e.term)===n||e.aliases.some(a=>normaliseFutsalText(a)===n))
}
