
const clamp=(v,a=2,b=98)=>Math.max(a,Math.min(b,v))
const D=(a,b)=>Math.hypot((a.x||0)-(b.x||0),(a.y||0)-(b.y||0))
const id=(p='i')=>p+Date.now().toString(36)+Math.random().toString(36).slice(2,7)
const RX=/(CANTO|CORNER|SA[IÍ]DA DE PRESS[ÃA]O|PRESS(?:URE)?\s*EXIT|LIVRE(?:\s+LATERAL|\s+CENTRAL)?|FREE\s*KICK|FORA|KICK[- ]?IN|BOLA DE SA[IÍ]DA|KICK[- ]?OFF|3\s*[:xX]\s*1|4\s*[:xX]\s*0|2\s*[:xX]\s*2|2\s*[:xX]\s*1|3\s*[:xX]\s*2|LINHAS DEFENSIVAS|TROCAS)/i
const cat=t=>{const x=(t||'').toLowerCase();if(/canto|corner/.test(x))return'Bola parada · Canto';if(/press/.test(x))return'Saída de pressão';if(/fora|lateral|kick.?in/.test(x))return'Bola parada · Fora';if(/livre|free kick/.test(x))return'Bola parada · Livre';if(/defens|linhas|trocas/.test(x))return'Tática defensiva';return'Importado'}
const step=(name='Passo 1')=>({id:id('s'),name,duration:1.1,players:[],ball:{x:50,y:50},paths:[]})
const imported=(title,source,steps,confidence,engine,notes=[])=>({id:id('imp'),title:title||'Tática importada',author:'Cavadas Manager · Interpreter V2',category:cat(title),phase:'Aquisição de competências',duration:10,objective:'',description:'Interpretação local automática. Rever elementos de baixa confiança antes do treino.',notes:['V19 · Interpreter V2',...notes].join(' · '),playersCount:steps[0]?.players?.length||0,field:'futsal',board:{players:steps[0]?.players||[],ball:steps[0]?.ball||{x:50,y:50},steps},source,imported:true,confidence:Math.round(Math.max(0,Math.min(100,confidence))),importEngine:engine,reviewRequired:confidence<82})
export function supportedImportKind(f){const n=(f?.name||'').toLowerCase(),t=f?.type||'';if(n.endsWith('.pdf')||t==='application/pdf')return'pdf';if(n.endsWith('.pptx'))return'pptx';if(/\.(mp4|webm|mov|m4v)$/i.test(n)||t.startsWith('video/'))return'video';if(/\.(png|jpe?g|webp|bmp)$/i.test(n)||t.startsWith('image/'))return'image';return'other'}
function hsv(r,g,b){r/=255;g/=255;b/=255;const M=Math.max(r,g,b),m=Math.min(r,g,b),d=M-m;let h=0;if(d){if(M===r)h=((g-b)/d)%6;else if(M===g)h=(b-r)/d+2;else h=(r-g)/d+4;h=(h*60+360)%360}return{h,s:M?d/M:0,v:M}}
function cc(mask,w,h,min=7,max=1e9){const seen=new Uint8Array(w*h),out=[];for(let i=0;i<mask.length;i++){if(!mask[i]||seen[i])continue;const q=[i];seen[i]=1;let qi=0,n=0,sx=0,sy=0,x0=w,y0=h,x1=0,y1=0;while(qi<q.length){const k=q[qi++],x=k%w,y=(k/w)|0;n++;sx+=x;sy+=y;x0=Math.min(x0,x);x1=Math.max(x1,x);y0=Math.min(y0,y);y1=Math.max(y1,y);for(const d of [1,-1,w,-w]){const j=k+d;if(j<0||j>=mask.length||seen[j]||!mask[j])continue;if((d===1&&j%w===0)||(d===-1&&k%w===0))continue;seen[j]=1;q.push(j)}}if(n>=min&&n<=max)out.push({n,cx:sx/n,cy:sy/n,minx:x0,maxx:x1,miny:y0,maxy:y1,w:x1-x0+1,h:y1-y0+1})}return out}
function vision(source,hand=false){
 const q=document.createElement('canvas'),r=Math.min(1,520/source.width,360/source.height);q.width=Math.max(80,Math.round(source.width*r));q.height=Math.max(80,Math.round(source.height*r));const c=q.getContext('2d',{willReadFrequently:true});c.drawImage(source,0,0,q.width,q.height);const w=q.width,h=q.height,d=c.getImageData(0,0,w,h).data,sat=new Uint8Array(w*h),dark=new Uint8Array(w*h)
 for(let i=0;i<w*h;i++){const j=i*4,H=hsv(d[j],d[j+1],d[j+2]);sat[i]=(H.s>.38&&H.v>.28&&!(H.h>70&&H.h<165))?1:0;dark[i]=((d[j]+d[j+1]+d[j+2])/3<92)?1:0}
 let cand=[...cc(sat,w,h,10,w*h*.035).map(x=>({...x,k:'sat'})),...cc(dark,w,h,8,w*h*.04).map(x=>({...x,k:'dark'}))].filter(x=>{const ar=x.w/Math.max(1,x.h),fill=x.n/(x.w*x.h);return ar>.48&&ar<2.1&&x.w>=4&&x.h>=4&&x.w<w*.18&&x.h<h*.22&&fill>(x.k==='sat'?.22:.08)})
 cand.sort((a,b)=>b.n-a.n);const ded=[];for(const x of cand)if(!ded.some(y=>Math.hypot(x.cx-y.cx,x.cy-y.cy)<Math.max(7,(x.w+y.w)/3)))ded.push(x)
 const sel=ded.slice(0,12),players=sel.map((x,i)=>{const j=(Math.round(x.cy)*w+Math.round(x.cx))*4,H=hsv(d[j]||0,d[j+1]||0,d[j+2]||0);return{id:'r'+i,team:x.k==='sat'&& (H.h<35||H.h>330)?'d':(i<5?'a':'d'),x:clamp(x.cx/w*100,4,96),y:clamp(x.cy/h*100,5,95),label:String((i%5)+1)}})
 const pm=dark.slice();for(const x of sel){const rr=Math.max(x.w,x.h)*.8+4;for(let yy=Math.max(0,Math.floor(x.cy-rr));yy<Math.min(h,Math.ceil(x.cy+rr));yy++)for(let xx=Math.max(0,Math.floor(x.cx-rr));xx<Math.min(w,Math.ceil(x.cx+rr));xx++)if(Math.hypot(xx-x.cx,yy-x.cy)<rr)pm[yy*w+xx]=0}
 const paths=[];for(const x of cc(pm,w,h,Math.max(10,w*h*.00012),w*h*.06)){const ar=Math.max(x.w,x.h)/Math.max(1,Math.min(x.w,x.h));if(ar<2||Math.max(x.w,x.h)<Math.min(w,h)*.07)continue;let a={x:x.minx/w*100,y:x.cy/h*100},b={x:x.maxx/w*100,y:x.cy/h*100};if(x.h>x.w){a={x:x.cx/w*100,y:x.miny/h*100};b={x:x.cx/w*100,y:x.maxy/h*100}}paths.push({id:id('p'),type:'move',x1:clamp(a.x),y1:clamp(a.y),x2:clamp(b.x),y2:clamp(b.y),candidate:true});if(paths.length>=12)break}
 const small=ded.filter(x=>x.w<Math.max(15,w*.045)&&x.h<Math.max(15,h*.06)).sort((a,b)=>a.n-b.n)[0],ball=small?{x:clamp(small.cx/w*100),y:clamp(small.cy/h*100)}:{x:50,y:50}
 return{players,paths,ball,confidence:Math.min(92,28+players.length*6+paths.length*2+(hand?4:8))}
}
function motionStep(s){const n={...step('Passo 2'),players:s.players.map(p=>({...p})),ball:{...s.ball},paths:[...s.paths]};for(const p of s.paths){const q=n.players.map(x=>({x,d:Math.hypot(x.x-p.x1,x.y-p.y1)})).sort((a,b)=>a.d-b.d)[0];if(q&&q.d<10){q.x.x=clamp(p.x2);q.x.y=clamp(p.y2)}}return n}
async function imageCanvas(file){const url=URL.createObjectURL(file);try{const im=new Image();await new Promise((a,b)=>{im.onload=a;im.onerror=b;im.src=url});const c=document.createElement('canvas');c.width=im.naturalWidth;c.height=im.naturalHeight;c.getContext('2d').drawImage(im,0,0);return c}finally{URL.revokeObjectURL(url)}}
async function image(file){const v=vision(await imageCanvas(file),true),s={...step('Esquema detetado'),players:v.players,ball:v.ball,paths:v.paths};return[imported(file.name.replace(/\.[^.]+$/,''),`${file.name} · imagem/manuscrito`,v.paths.length?[s,motionStep(s)]:[s],v.confidence,'Imagem/Manuscrito V2',[`${v.players.length} peças candidatas`,`${v.paths.length} trajetórias candidatas`])]}
async function pdf(file,setProgress){const P=await import('pdfjs-dist/legacy/build/pdf.mjs');try{P.GlobalWorkerOptions.workerSrc=new URL('pdfjs-dist/legacy/build/pdf.worker.mjs',import.meta.url).toString()}catch{}const doc=await P.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise,out=[],N=Math.min(doc.numPages,40);for(let n=1;n<=N;n++){const pg=await doc.getPage(n),tx=await pg.getTextContent(),raw=tx.items.map(x=>x.str).join(' ').replace(/\s+/g,' ').trim(),m=raw.match(RX),vp=pg.getViewport({scale:1.1}),c=document.createElement('canvas'),sc=Math.min(1,1200/vp.width,850/vp.height);c.width=Math.round(vp.width*sc);c.height=Math.round(vp.height*sc);await pg.render({canvasContext:c.getContext('2d'),viewport:pg.getViewport({scale:1.1*sc})}).promise;const v=vision(c),s={...step('Passo 1'),players:v.players,ball:v.ball,paths:v.paths};if(m||v.players.length>=3)out.push(imported(`${(m?.[0]||raw.slice(0,55)||'Esquema').trim()} · pág. ${n}`,`${file.name} · PDF pág. ${n}`,v.paths.length?[s,motionStep(s)]:[s],Math.min(95,v.confidence+(m?10:0)),'PDF Vision V2',[`${v.players.length} peças`,`${v.paths.length} trajetórias`,`renderização real da página`]));setProgress?.(Math.round(n/N*100))}if(!out.length)throw new Error('Não foi possível reconhecer um esquema tático neste PDF.');return out}
const text=(n,t)=>[...n.getElementsByTagName(t)].map(x=>x.textContent||'').join(' ').trim()
const tag=(n,...ts)=>{for(const t of ts){const x=n.getElementsByTagName(t)[0];if(x)return x}return null}
function ppath(s=''){const a=(s.match(/-?\d*\.?\d+(?:e[-+]?\d+)?/ig)||[]).map(Number);return a.length>=4?{dx:a[a.length-2]-a[0],dy:a[a.length-1]-a[1]}:null}
async function pptx(file,setProgress){const Z=(await import('jszip')).default,z=await Z.loadAsync(await file.arrayBuffer()),P=new DOMParser();let sw=12192000,sh=6858000;const pf=z.file('ppt/presentation.xml');if(pf){const x=P.parseFromString(await pf.async('text'),'application/xml'),sz=tag(x,'p:sldSz','sldSz');if(sz){sw=+sz.getAttribute('cx')||sw;sh=+sz.getAttribute('cy')||sh}}const slides=Object.keys(z.files).filter(x=>/^ppt\/slides\/slide\d+\.xml$/.test(x)).sort((a,b)=>+a.match(/\d+/)[0]-+b.match(/\d+/)[0]),out=[];for(let si=0;si<slides.length;si++){const path=slides[si],n=+path.match(/slide(\d+)/)[1],x=P.parseFromString(await z.file(path).async('text'),'application/xml'),raw=text(x,'a:t')||text(x,'t'),m=raw.match(RX),players=[],by=new Map();for(const sp of [...x.getElementsByTagName('p:sp'),...x.getElementsByTagName('p:pic')]){const nv=tag(sp,'p:cNvPr','cNvPr'),sid=nv?.getAttribute('id')||String(players.length+1),name=nv?.getAttribute('name')||'',label=text(sp,'a:t')||text(sp,'t')||name,off=tag(sp,'a:off','off'),ext=tag(sp,'a:ext','ext');if(!off)continue;const X=+off.getAttribute('x')||0,Y=+off.getAttribute('y')||0,W=+ext?.getAttribute('cx')||0,H=+ext?.getAttribute('cy')||0;if(/^\s*\d{1,2}\s*$/.test(label)||/GR|GK|PLAYER|JOG/i.test(label)){const o={id:'ppt'+sid,pptShapeId:sid,team:players.length<5?'a':'d',x:clamp((X+W/2)/sw*100),y:clamp((Y+H/2)/sh*100),label:(label.match(/\d{1,2}/)||[])[0]||(/GR|GK/i.test(label)?'GR':String(players.length+1))};players.push(o);by.set(sid,o)}}const motions=[];for(const a of [...x.getElementsByTagName('p:animMotion'),...x.getElementsByTagName('animMotion')]){const sid=tag(a,'p:spTgt','spTgt')?.getAttribute('spid'),q=ppath(a.getAttribute('path')||'');if(sid&&q&&by.has(sid))motions.push({sid,...q})}if(m||motions.length||players.length>=3){let cur={...step('Posição inicial'),players:players.map(p=>({...p})),ball:{x:50,y:50},paths:[]},steps=[cur];for(const [k,a] of motions.slice(0,20).entries()){const nx={...step(`Movimento ${k+1}`),players:cur.players.map(p=>({...p})),ball:{...cur.ball},paths:[]},p=nx.players.find(q=>String(q.pptShapeId)===String(a.sid));if(p){const f={x:p.x,y:p.y};p.x=clamp(p.x+a.dx*100);p.y=clamp(p.y+a.dy*100);nx.paths.push({id:id('m'),type:'move',x1:f.x,y1:f.y,x2:p.x,y2:p.y})}steps.push(nx);cur=nx}out.push(imported(`${(m?.[0]||raw.slice(0,55)||'Slide').trim()} · slide ${n}`,`${file.name} · PPTX slide ${n}`,steps,Math.min(98,45+(players.length>=3?18:0)+(motions.length?30:0)+(m?7:0)),'PPTX Motion V2',[`${players.length} peças por geometria`,`${motions.length} p:animMotion`, `dimensão real do slide`]))}setProgress?.(Math.round((si+1)/slides.length*100))}if(!out.length)throw new Error('O PPTX não contém objetos táticos reconhecíveis.');return out}
function comps(ctx,w,h){const d=ctx.getImageData(0,0,w,h).data,m=new Uint8Array(w*h),meta=[];for(let i=0;i<w*h;i++){const j=i*4,H=hsv(d[j],d[j+1],d[j+2]);meta[i]=H;m[i]=(H.s>.42&&H.v>.34&&!(H.h>72&&H.h<165))?1:0}return cc(m,w,h,7,w*h*.02).filter(x=>{const ar=x.w/Math.max(1,x.h),f=x.n/(x.w*x.h);return ar>.45&&ar<2.2&&f>.16&&x.w>=3&&x.h>=3&&x.w<w*.14&&x.h<h*.19}).slice(0,16).map(x=>{const H=meta[Math.min(meta.length-1,Math.round(x.cy)*w+Math.round(x.cx))]||{};return{x:x.cx/w*100,y:x.cy/h*100,...H}})}
async function video(file,setProgress){const u=URL.createObjectURL(file),v=document.createElement('video');v.src=u;v.muted=true;v.playsInline=true;try{await new Promise((a,b)=>{v.onloadedmetadata=a;v.onerror=b});const dur=Math.min(v.duration||20,120),N=Math.max(12,Math.min(42,Math.ceil(dur*1.5))),c=document.createElement('canvas');c.width=480;c.height=270;const ctx=c.getContext('2d',{willReadFrequently:true}),frames=[];let prev=[],seq=1;for(let i=0;i<N;i++){v.currentTime=dur*(i/(N-1));await new Promise(a=>v.onseeked=a);ctx.drawImage(v,0,0,c.width,c.height);const raw=comps(ctx,c.width,c.height),used=new Set(),now=[];for(const p of raw){let best=null;for(let k=0;k<prev.length;k++){if(used.has(k))continue;const q=prev[k],sc=D(p,q)+Math.abs((p.h||0)-(q.h||0))/18;if(!best||sc<best.sc)best={k,q,sc}}if(best&&best.sc<14){used.add(best.k);now.push({...p,id:best.q.id,label:best.q.label,team:best.q.team})}else now.push({...p,id:'v'+seq,label:String(((seq++-1)%5)+1),team:(p.h<35||p.h>330)?'d':'a'})}prev=now;frames.push({...step(`Frame ${i+1}`),duration:Math.max(.45,dur/(N-1)),players:now.map(p=>({id:p.id,team:p.team,x:p.x,y:p.y,label:p.label})),ball:{x:50,y:50},paths:[]});setProgress?.(Math.round((i+1)/N*100))}const avg=frames.reduce((a,s)=>a+s.players.length,0)/frames.length;if(avg<2)throw new Error('O vídeo não tem marcadores táticos suficientemente nítidos para seguimento automático.');const keep=[frames[0]];for(let i=1;i<frames.length-1;i++){const a=keep[keep.length-1],b=frames[i];let mv=0,n=0;for(const p of b.players){const q=a.players.find(x=>x.id===p.id);if(q){mv+=D(p,q);n++}}if(n&&mv/n>2.2)keep.push(b)}keep.push(frames.at(-1));const steps=keep.slice(0,18).map((x,i)=>({...x,name:`Passo ${i+1}`}));return[imported(file.name.replace(/\.[^.]+$/,''),`${file.name} · vídeo ${dur.toFixed(1)} s`,steps,Math.min(91,40+avg*5+15),'Video Tracking V2',[`${N} amostras`,`IDs por proximidade/cor`,`sem fallback inventado`])]}finally{URL.revokeObjectURL(u)}}
export async function analyseDocumentV2(file,setProgress){const k=supportedImportKind(file);if(k==='pdf')return pdf(file,setProgress);if(k==='pptx')return pptx(file,setProgress);if(k==='video')return video(file,setProgress);if(k==='image')return image(file);throw new Error('Formato suportado: PDF, PPTX, imagem ou vídeo.')}
